spring:
   datasource:
      name: master
#      driver-class-name: com.mysql.jdbc.Driver  mysql8中过时了
      driver-class-name: com.mysql.cj.jdbc.Driver
#    mysql8.0版本要加时区  serverTimezone=UTC
      url: jdbc:mysql://47.92.155.150:12306/sunboxiot?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: PFxcd123$%^
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      # WebStatFilter配置
      web-stat-filter:
         enabled: true
         # 添加过滤规则
         url-pattern: /*
         # 忽略过滤的格式
         exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
         enabled: true
         # 访问路径为/druid时，跳转到StatViewServlet
         url-pattern: /druid/*
         # 是否能够重置数据
         reset-enable: false
         # 需要账号密码才能访问控制台
         login-username: druid
         login-password: druid123
   redis:
      host: 139.224.74.177
      port: 6379
      password: I][3^QzL8Dl)[7f
      pool:
         max-active: 8
         max-idle: 8
         min-idle: 0
         max-wait: 10000
#      出现相同bean名称启动报错,可以临时覆盖解决,最好找到问题,相同bean需要改名称
#   main:
#      allow-bean-definition-overriding: true
   flyway:
      enabled: true
      # 禁止清理数据库表
      clean-disabled: true
      # 如果数据库不是空表，需要设置成 true，否则启动报错
      baseline-on-migrate: true
      # 与 baseline-on-migrate: true 搭配使用
      baseline-version: 1
#      （根据个人情况设置）
      locations: classpath:db/migration/mysql
   thymeleaf:
      cache: false
mybatis-plus:
   # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
   mapper-locations: classpath:/mapper/*.xml
#   type-aliases-package: com.breakeyizhan.web.model
   # 以下配置均有默认值,可以不设置
   global-config:
      db-config:
         # 主键类型,大小写不敏感 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
         id-type: auto
         # 字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
         field-strategy: not_empty
         #数据库类型, 大小写不敏感
         db-type: mysql
   configuration:
      # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
      map-underscore-to-camel-case: true
      # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
      call-setters-on-nulls: false
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用####
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
   port: 8080
   contextPath: /
logging:
   level:
      com.breakeyizhan.web.dao: DEBUG